/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var interpreter = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,5],$V1=[5,7],$V2=[1,23],$V3=[1,24],$V4=[1,25],$V5=[1,27],$V6=[1,28],$V7=[1,29],$V8=[1,30],$V9=[8,13,25,28,32,36,49,52],$Va=[1,53],$Vb=[1,52],$Vc=[1,51],$Vd=[8,38,53],$Ve=[2,39],$Vf=[1,58],$Vg=[10,18,37,38,39,40,41,42,43,44,45,46,51],$Vh=[18,29];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"INICIO":3,"GLOBALES":4,"EOF":5,"DECLARAR_FUNCIONES":6,"void":7,"id":8,"(":9,")":10,"CUERPO":11,"{":12,"}":13,"INSTRUCCIONES":14,"INSTRUCCION":15,"LABEL":16,"IF":17,";":18,"GOTO":19,"FUNCION":20,"EXPRESION":21,"PRINT":22,"RETURN":23,":":24,"if":25,"VALOR":26,"RELATIONAL":27,"goto":28,"=":29,"ARITHMETIC":30,"STRUCTURE":31,"printf":32,"cadena":33,",":34,"CASTEO":35,"return":36,"+":37,"-":38,"*":39,"/":40,">":41,">=":42,"<":43,"<=":44,"==":45,"!=":46,"float":47,"int":48,"Stack":49,"[":50,"]":51,"Heap":52,"number":53,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"void",8:"id",9:"(",10:")",12:"{",13:"}",18:";",24:":",25:"if",28:"goto",29:"=",32:"printf",33:"cadena",34:",",36:"return",37:"+",38:"-",39:"*",40:"/",41:">",42:">=",43:"<",44:"<=",45:"==",46:"!=",47:"float",48:"int",49:"Stack",50:"[",51:"]",52:"Heap",53:"number"},
productions_: [0,[3,2],[3,1],[4,2],[4,1],[6,5],[11,2],[11,3],[14,2],[14,1],[15,1],[15,2],[15,2],[15,2],[15,2],[15,2],[15,2],[16,2],[17,8],[19,2],[20,3],[21,5],[21,3],[21,3],[21,3],[22,7],[23,1],[30,1],[30,1],[30,1],[30,1],[27,1],[27,1],[27,1],[27,1],[27,1],[27,1],[35,3],[35,3],[35,0],[31,5],[31,5],[26,1],[26,2],[26,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
return $$[$0-1]
break;
case 3:
$$[$0-1].push($$[$0]);this.$=$$[$0-1];
break;
case 4:
this.$=[$$[$0]];
break;
case 5:
this.$=new FunctionC3D($$[$0-4],$$[$0-3],$$[$0],_$[$0-4].first_line, _$[$0-4].first_column)
break;
case 6:
this.$=[]
break;
case 7: case 11: case 12: case 13: case 14: case 15: case 16:
this.$=$$[$0-1]
break;
case 8:
$$[$0-1].push($$[$0]);this.$ = $$[$0-1];
break;
case 9:
this.$ = [$$[$0]];
break;
case 10: case 27: case 28: case 29: case 30: case 31: case 32: case 33: case 34: case 35: case 36:
this.$=$$[$0]
break;
case 17:
this.$=new Label($$[$0-1],_$[$0-1].first_line, _$[$0-1].first_column)
break;
case 18:
this.$=new Conditional($$[$0-5],$$[$0-4],$$[$0-3],$$[$0],_$[$0-7].first_line, _$[$0-7].first_column)
break;
case 19:
this.$=new Goto($$[$0],_$[$0-1].first_line, _$[$0-1].first_column)
break;
case 20:
this.$=new AccessC3D($$[$0-2],_$[$0-2].first_line, _$[$0-2].first_column)
break;
case 21:
this.$=new ExpressionC3D(_$[$0-4].first_line, _$[$0-4].first_column,$$[$0-4],$$[$0-2],$$[$0],$$[$0-1])
break;
case 22: case 23: case 24:
this.$=new ExpressionC3D(_$[$0-2].first_line, _$[$0-2].first_column,$$[$0-2],$$[$0])
break;
case 25:
this.$=new Print($$[$0-4],$$[$0-1],_$[$0-6].first_line, _$[$0-6].first_column)
break;
case 26:
this.$=new ReturnC3D(_$[$0].first_line, _$[$0].first_column)
break;
case 37: case 38:
this.$=$$[$0-2]+$$[$0-1]+$$[$0]
break;
case 39:
this.$=""
break;
case 40: case 41:
this.$=$$[$0-4]+","+$$[$0-1]
break;
case 42: case 44:
this.$ = $$[$0]
break;
case 43:
this.$ = $$[$0-1]+$$[$0]
break;
}
},
table: [{3:1,4:2,5:[1,3],6:4,7:$V0},{1:[3]},{5:[1,6],6:7,7:$V0},{1:[2,2]},o($V1,[2,4]),{8:[1,8]},{1:[2,1]},o($V1,[2,3]),{9:[1,9]},{10:[1,10]},{11:11,12:[1,12]},o($V1,[2,5]),{8:$V2,13:[1,13],14:14,15:15,16:16,17:17,19:18,20:19,21:20,22:21,23:22,25:$V3,28:$V4,31:26,32:$V5,36:$V6,49:$V7,52:$V8},o($V1,[2,6]),{8:$V2,13:[1,31],15:32,16:16,17:17,19:18,20:19,21:20,22:21,23:22,25:$V3,28:$V4,31:26,32:$V5,36:$V6,49:$V7,52:$V8},o($V9,[2,9]),o($V9,[2,10]),{18:[1,33]},{18:[1,34]},{18:[1,35]},{18:[1,36]},{18:[1,37]},{18:[1,38]},{9:[1,40],24:[1,39],29:[1,41]},{9:[1,42]},{8:[1,43]},{29:[1,44]},{9:[1,45]},{18:[2,26]},{50:[1,46]},{50:[1,47]},o($V1,[2,7]),o($V9,[2,8]),o($V9,[2,11]),o($V9,[2,12]),o($V9,[2,13]),o($V9,[2,14]),o($V9,[2,15]),o($V9,[2,16]),o($V9,[2,17]),{10:[1,48]},{8:$Va,26:49,31:50,38:$Vb,49:$V7,52:$V8,53:$Vc},{8:$Va,26:54,38:$Vb,53:$Vc},{18:[2,19]},{8:$Va,26:55,38:$Vb,53:$Vc},{33:[1,56]},o($Vd,$Ve,{35:57,9:$Vf}),o($Vd,$Ve,{35:59,9:$Vf}),{18:[2,20]},{18:[2,22],30:60,37:[1,61],38:[1,62],39:[1,63],40:[1,64]},{18:[2,23]},o($Vg,[2,42]),{53:[1,65]},o($Vg,[2,44]),{27:66,41:[1,67],42:[1,68],43:[1,69],44:[1,70],45:[1,71],46:[1,72]},{18:[2,24]},{34:[1,73]},{8:$Va,26:74,38:$Vb,53:$Vc},{47:[1,75],48:[1,76]},{8:$Va,26:77,38:$Vb,53:$Vc},{8:$Va,26:78,38:$Vb,53:$Vc},o($Vd,[2,27]),o($Vd,[2,28]),o($Vd,[2,29]),o($Vd,[2,30]),o($Vg,[2,43]),{8:$Va,26:79,38:$Vb,53:$Vc},o($Vd,[2,31]),o($Vd,[2,32]),o($Vd,[2,33]),o($Vd,[2,34]),o($Vd,[2,35]),o($Vd,[2,36]),o($Vd,$Ve,{35:80,9:$Vf}),{51:[1,81]},{10:[1,82]},{10:[1,83]},{51:[1,84]},{18:[2,21]},{10:[1,85]},{8:$Va,26:86,38:$Vb,53:$Vc},o($Vh,[2,40]),o($Vd,[2,37]),o($Vd,[2,38]),o($Vh,[2,41]),{28:[1,87]},{10:[1,88]},{8:[1,89]},{18:[2,25]},{18:[2,18]}],
defaultActions: {3:[2,2],6:[2,1],28:[2,26],43:[2,19],48:[2,20],50:[2,23],55:[2,24],78:[2,21],88:[2,25],89:[2,18]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

    const {FunctionC3D} = require('../interpreter/instruction/Function');
    const {Conditional} = require('../interpreter/instruction/Conditional');
    const {Label} = require('../interpreter/instruction/Label');
    const {Goto} = require('../interpreter/instruction/Goto');
    const {AccessC3D} = require('../interpreter/instruction/Access');
    const {Print} = require('../interpreter/instruction/Print');
    const {ReturnC3D} = require('../interpreter/instruction/Return');
    const {ExpressionC3D} = require('../interpreter/instruction/Expression');
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:// ignora los espacios en blanco
break;
case 1:// comentario de linea
break;
case 2:// comentario de multiples lineas	
break;
case 3:return 53
break;
case 4:return 'double'
break;
case 5:return 7
break;
case 6:return 48
break;
case 7:return 47
break;
case 8:return "return"
break;
case 9:return "if";
break;
case 10:return "goto";
break;
case 11:return "Stack";
break;
case 12:return "Heap";
break;
case 13:return "printf"
break;
case 14:return ","
break;
case 15:return 24;
break;
case 16:return ";";
break;
case 17:return 12;
break;
case 18:return 13;
break;
case 19:return 9;
break;
case 20:return 10;
break;
case 21:return 50
break;
case 22:return 51                   
break;
case 23:return 44;
break;
case 24:return 42;
break;
case 25:return 45;
break;
case 26:return 46;
break;
case 27:return 37;
break;
case 28:return 38;
break;
case 29:return 39;
break;
case 30:return 40;
break;
case 31:return 43;
break;
case 32:return 41;
break;
case 33:return 29;
break;
case 34: yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 33; 
break;
case 35:return 8;
break;
case 36:return 5;
break;
case 37:return 'ERROR'
break;
}
},
rules: [/^(?:\s+)/,/^(?:\/\/.*)/,/^(?:[/][*][^*]*[*]+([^/*][^*]*[*]+)*[/])/,/^(?:(([0-9]+)(\.([0-9]+))?))/,/^(?:double\b)/,/^(?:void\b)/,/^(?:int\b)/,/^(?:float\b)/,/^(?:return\b)/,/^(?:if\b)/,/^(?:goto\b)/,/^(?:Stack\b)/,/^(?:Heap\b)/,/^(?:printf\b)/,/^(?:,)/,/^(?::)/,/^(?:;)/,/^(?:\{)/,/^(?:\})/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?:<=)/,/^(?:>=)/,/^(?:==)/,/^(?:!=)/,/^(?:\+)/,/^(?:-)/,/^(?:\*)/,/^(?:\/)/,/^(?:<)/,/^(?:>)/,/^(?:=)/,/^(?:"([^\\\"]|\\.)*")/,/^(?:([a-zA-Z_])[a-zA-Z0-9_]*)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = interpreter;
exports.Parser = interpreter.Parser;
exports.parse = function () { return interpreter.parse.apply(interpreter, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}